### ISSUE TITLE
doesn't work for me

### ISSUE THREAD

**Issue by schel4ok** [orchestral/imagine#10]
Hello,

I can't understand how to get your extension work in Laravel 4.2
I just made a controller
<?php
use Imagine\Image\Box;
use Imagine\Image\ImageInterface;

class ImageController extends BaseController {

	public function create_thumbnail()
{
    $width  = 320;
    $height = 320;
    $mode   = ImageInterface::THUMBNAIL_OUTBOUND;
    $size   = new Box($width, $height);
    $thumbnail   = Imagine::open('img/header.jpg')->thumbnail($size, $mode);
    $destination = 'img/header.thumb.jpg';
    $thumbnail->save($destination);
    return "thumbnail created";
}

in router.php 
Route::get('gallery/thumb', 'ImageController@create_thumbnail');

and I got empty page and thumbnail is not created in img folder

**Comment by crynobone** [comment]
You need to include a full path to `'img/header.jpg'`, Imagine can't just magically know the file location, provide a full path.

**Comment by schel4ok** [comment]
img folder located just in public

so for example this works fine
		$files = File::allFiles('img');
		foreach ($files as $file)
		{   echo '<img src="'. $file .'" alt="foto"><br>';   }

**Comment by crynobone** [comment]
Above code are Laravel, for Imagine we don't dictate how you want to store your file, you could either use public directory, storage directory and only allow access from a controller or etc. Again **provide a full path** is how you solve this.

**Comment by schel4ok** [comment]
I tried like this
    $thumbnail   = Imagine::open(public_path().'img/header.jpg')->thumbnail($size, $mode);
    $destination = public_path().'img/header.thumb.jpg';

and like this
    $thumbnail   = Imagine::open(public_path().'/img/header.jpg')->thumbnail($size, $mode);
    $destination = public_path().'/img/header.thumb.jpg';

but no success. I even don't have any error page. Just white blank page.

**Comment by crynobone** [comment]
Have you look in Laravel error logs?

**Comment by schel4ok** [comment]
last error I have in log file is about wrong template file, not about ImageController or wrong path to file

**Comment by crynobone** [comment]
Fresh Laravel 4.2 with Imagine 2.2 configured:

```php
<?php

use Imagine\Image\Box;
use Imagine\Image\ImageInterface;
use Orchestra\Imagine\ImagineManager;
use Orchestra\Imagine\Facade as Imagine;

function create_thumbnail($path, $filename, $extension)
{
    $width  = 320;
    $height = 320;
    $mode   = ImageInterface::THUMBNAIL_OUTBOUND;
    $size   = new Box($width, $height);

    $thumbnail   = Imagine::open("{$path}/{$filename}.{$extension}")->thumbnail($size, $mode);
    $destination = "{$filename}.thumb.{$extension}";

    $thumbnail->save("{$path}/{$destination}");
}

Route::get('/', function()
{
	create_thumbnail(public_path(), 'adam', 'jpg');

	return View::make('hello');
});
```

![screen shot 2015-03-05 at 12 27 46 am](https://cloud.githubusercontent.com/assets/172966/6487864/91ac9604-c2ce-11e4-9531-9226436b59e2.png)

**Comment by crynobone** [comment]
So I not sure how I can replicate this issue, I might be related to GD <http://stackoverflow.com/questions/5531105/php-gd-always-shows-blank-page>
