### ISSUE TITLE
Imagick 

### ISSUE THREAD

**Issue by schel4ok** [orchestral/imagine#11]
Now I try imagine with Laravel 5.0
I tried to use ->resize(new Box(320, 240), ImageInterface::FILTER_LANCZOS)
and get error
Unsupported filter type, GD only supports ImageInterface::FILTER_UNDEFINED filter

I make sure that php_imagick.dll is not commented in my php.ini.
Is it possible to set in my file that I want to use imagick instead gd?

**Comment by crynobone** [comment]
```php
<?php namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class ConfigServiceProvider extends ServiceProvider
{
    /**
     * Overwrite any vendor / package configuration.
     *
     * This service provider is intended to provide a convenient location for you
     * to overwrite any "vendor" or package configuration that you may want to
     * modify before the application handles the incoming request / command.
     *
     * @return void
     */
    public function register()
    {
        config([
            'orchestra/imagine::driver' => 'imagick',
        ]);
    }
}
```

**Comment by varmad** [comment]
Is ther any way to publish config file like in Laravel 4?

**Comment by crynobone** [comment]
> Is ther any way to publish config file like in Laravel 4?

Not at the moment.

**Comment by crynobone** [comment]
@varmad https://github.com/orchestral/imagine/releases/tag/v3.0.1
