### ISSUE TITLE
how to show images from not public folder

### ISSUE THREAD

**Issue by schel4ok** [orchestral/imagine#12]
Could you help me to find a way how to show images from not public folder on the web-site using your plugin?
Because what I found from documentation is only  ->show('jpg')  method.

foreach ($files as $file) 
{   $thumbnail   = Imagine::open(base_path().'/'.$file)
    			->thumbnail($size, $mode)
    			->save(base_path().'/'.$img_path)
    			->show('jpg');
}

return view('thumbs')->withFiles($files)->withThumbnail($thumbnail);

If I do so in controller program die just after  ->show  and output the first thumbnail in array.
So I can never reach my blade template.
But I want to have $thumbnail object with all image names to be accessible through my blade template

to make something like this
@foreach ($thumbnails as $thumbnail)
img src= {{ $thumbnail->name }}
@endforeach

**Comment by crynobone** [comment]
Not part of plugin/package responsibility.
