### ISSUE TITLE
error with watermark

### ISSUE THREAD

**Issue by schel4ok** [orchestral/imagine#13]
function create_thumbnails()
{
    $width  = 640;
    $height = 480;
    $size   = new Box($width, $height);
    $mode   = ImageInterface::THUMBNAIL_INSET;   

    $img_path = 'img/';
    $thumb_path = 'img/thumbs/';
    $files = str_replace('\\', '/', Storage::files($img_path));
	$watermark = Imagine::open(base_path().'/resources/assets/watermark/watermark-2.png');
	$wSize     = $watermark->getSize();  // 350x250
	$bottomRight = new Point($size->getWidth() - $wSize->getWidth(), $size->getHeight() - $wSize->getHeight());

    foreach ($files as $file) 
    {
	    $thumbnail   = Imagine::open(public_path().'/'.$file)
    					->thumbnail($size, $mode)
    					->paste($watermark, $bottomRight)
    					->save(public_path().'/'.str_replace($img_path, $thumb_path, $file), array('jpeg_quality' => 75));
     }

}

gives an error
OutOfBoundsException in Image.php line 208:
Cannot paste image of the given size at the specified position, as it moves outside of the current image's box

image size of pictures in img folder is 2448x3264
so actually I don't understand what's wrong

when I comment ->paste everything is ok.

**Comment by crynobone** [comment]
This package only handle wrapping Imagine library request to manipulate images. Please go the correct repository if you have problem using any of the library code.

https://github.com/avalanche123/Imagine/issues
