### ISSUE TITLE
Imagick not installed

### ISSUE THREAD

**Issue by onalekitso** [orchestral/imagine#16]
After Mac OS X upgrade to El Capitan I have an Imagick (Imagick not installed) error but my php info should it has been installed and enabled. I have also check the extension using

if (!extension_loaded('imagick'))
    echo 'imagick not installed';
else
    echo 'Installed';

Please find the attached files.

![screen shot 2015-10-04 at 11 49 58 pm](https://cloud.githubusercontent.com/assets/6186801/10276266/ac5aae2c-6b4e-11e5-91ce-be98ecace0e8.png)
![screen shot 2015-10-04 at 11 50 02 pm](https://cloud.githubusercontent.com/assets/6186801/10276265/ac5a8992-6b4e-11e5-817e-0986ecf2284f.png)

**Comment by crynobone** [comment]
What the output of:

```php
Imagick::getVersion();
```

**Comment by onalekitso** [comment]
The output is 
String: ImageMagick 6.9.1-10 Q16 x86_64 2015-09-11 http://www.imagemagick.org

**Comment by crynobone** [comment]
Are you sure you're running on the same PHP installation for both `localhost:80` and `127.0.0.1:8000`?

**Comment by onalekitso** [comment]
Yes sir, 127.0.0.1:8000 is an instance of symfony2 "app/console server:run" command. I will relook into my configurations. Thank you
