### ISSUE TITLE
why the .gif image will be without animation

### ISSUE THREAD

**Issue by xenkocz** [orchestral/imagine#17]
if i use this code: Imagine::open($src_path)->save($des_path);

When i use it so it becomes a static image from gif, but only when it moved with
$file->move(...) so it works fine.
Among other things, using laravel 5.1 and GD and Imagick are current version.

**Comment by crynobone** [comment]
Based on our description.

> Imagine (Wrapper) Component is a Laravel 5 package wrapper for Imagine (<https://github.com/avalanche123/Imagine>).
