### ISSUE TITLE
Add values to enable auto-discovery in Laravel 5.5

### ISSUE THREAD

**Issue by rchoffardet** [orchestral/imagine#19]
Hello,

I recently made a very simple self-explanatory pull-request to enable auto-discovery for this package. Why did you close it ?
No backward-incompatibilities, installation and configuration would be easier. 
I don't get it.

Regards,
Robin

**Comment by crynobone** [comment]
We're not planning to support auto-discovery especially on adding "facades".

And furthermore, failing tests. https://travis-ci.org/orchestral/imagine/builds/317363181

**Comment by rchoffardet** [comment]
If I fix these mistakes, is there any chance that you'll accept these changes ?

**Comment by crynobone** [comment]
nope

https://twitter.com/crynobone/status/942603922266394624
