### ISSUE TITLE
composer not updatating the package 

### ISSUE THREAD

**Issue by dbhosale** [orchestral/imagine#4]
I received following error while updating through composer 
Problem 1
    - remove orchestra/imagine 3.0.x-dev|keep orchestra/imagine dev-master
    - orchestra/imagine 3.0.x-dev requires orchestra/support-providers 3.0.\* -> no matching package found.
    - orchestra/imagine dev-master requires orchestra/support-providers 3.0.\* -> no matching package found.
    - Installation request for orchestra/imagine 3.0.*@dev -> satisfiable by orchestra/imagine[3.0.x-dev].

**Comment by schel4ok** [comment]
I tried to install "orchestra/imagine": "3.1.*" on laravel 5.0

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package orchestra/imagine could not be found in any version, there may be a typo in the package name.

**Comment by crynobone** [comment]
@schel4ok `"orchestra/imagine": "3.1.*"` is for Laravel 5.1,

See <https://github.com/orchestral/imagine#version-compatibility>
