### ISSUE TITLE
Class 'App\Http\Controllers\Imagine' not found

### ISSUE THREAD

**Issue by kayintveen** [orchestral/imagine#7]
I added the example code to my existing ImagesController. 

```

	public function create_thumbnail($path, $filename, $extension)
	{
	    $width  = 320;
	    $height = 320;
	    $mode   = ImageInterface::THUMBNAIL_OUTBOUND;
	    $size   = new Box($width, $height);

	    $thumbnail   = Imagine::open("{$path}/{$filename}.{$extension}")->thumbnail($size, $mode);
	    $destination = "{$filename}.thumb.{$extension}";

	    $thumbnail->save("{$path}/{$destination}");
	}
```

Also i added 

```
use Imagine\Image\Box;

use Imagine\Image\ImageInterface;
```

i followed all steps carefully installed 3.0 for laravel 5.0 im using.

**Comment by crynobone** [comment]
you need to include following as well:

```php
use Imagine;
```

**Comment by kayintveen** [comment]
Wow so easy, great support thanks!

**Comment by goedda** [comment]
Could this be added to the 'README.md' file?
And maybe also a note that the config folder in Laravel 5 by default is ROOT/config/ and not ROOT/app/config/

Would appreciate it. Thanks for the nice package!

**Comment by crynobone** [comment]
Adding `use Imagine` is something that you have to get used with working on namespaced project.

**Comment by kayintveen** [comment]
When i want to add it to a command for example, i then cannot use just use Imagine right?

**Comment by crynobone** [comment]
It depends where you're working under any namespace, recommend to read up a bit on PHP namespacing.

**Comment by riyadfebrian** [comment]
thanks for sharing the issue
