### ISSUE TITLE
can't update my project for laravel 5

### ISSUE THREAD

**Issue by schel4ok** [orchestral/imagine#9]
I tried to install "orchestra/imagine": "3.1.*" on laravel 5.0

Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package orchestra/imagine could not be found in any version, there may be a typo in the package name.

**Comment by crynobone** [comment]
@schel4ok `"orchestra/imagine": "3.1.*"` is for Laravel 5.1,

See <https://github.com/orchestral/imagine#version-compatibility>
